# Generated by Django 5.0.6 on 2024-07-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cart_remove_order_listing_id_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_provider',
        ),
    ]
