# Generated by Django 5.0.6 on 2024-07-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_delivery_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Momo'), ('cash', 'Cash')], default='cash', max_length=255),
        ),
    ]
